### ISSUE TITLE
刚刚在ANKI teltegram群里的一个链接

### ISSUE THREAD

**Issue by kunpeng9** [L-M-Sherlock/AnkigaokaoTutorial#1]
https://yiufung.net/post/anki-org/     @L-M-Sherlock 
或许你可以看一下。。。。
已在anki高考群里面，而且还买了你的电工的卡包，我向我们班的同学推荐这个【希望可以有点合作，也是你的知乎文章给了我启发，虽然目前还没搞清楚怎么用那个 】但是他们都不予理会的，前阵子考研的时候时常喘喘不安跑到我寝室和我也考研的室友交流。。什么数学前面做了后面又忘了。。。真是郁闷(＃￣～￣＃)，我向他们推荐方法他们又说有自己的方法，这算是成年人的固执与思维固化吗？
这个issue是相当于Tim的 @嘛。。。学计算机的真是占了先机，还可以编写插件等等，我学机械电子的，虽然学过C语言 选修过 Python 但是链接里的代码还是看不懂。。。感觉差了好远。。。

**Comment by L-M-Sherlock** [comment]
这个姿势水平有点高，我虽然也是学计算机的，但是对插件什么的没有什么想法。我看看寒假找找有没有 markdown 自动切分导入卡片的插件，如果没有，我考虑写一个。
